services:
  # Redis for LiveKit
  redis:
    image: redis:6-alpine
    container_name: livekit-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - livekit-network

  # LiveKit Server
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: unless-stopped
    command: --config /livekit.yaml
    volumes:
      - ./callserver_deepfakePy/livekit-services/livekit.yaml:/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
    environment:
      - LIVEKIT_EXTERNAL_IP=localhost
      - LIVEKIT_HOST=0.0.0.0
      - LIVEKIT_PORT=7880
    networks:
      - livekit-network
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  livekit-network:
    driver: bridge