version: "3.8"

services:
  # 1. LiveKit Server
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: unless-stopped
    command: --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml
    ports:
      # Signaling (required)
      - "7880:7880"
      # WebRTC over TCP (required)
      - "7881:7881"
      # WebRTC UDP port range for media
      - "50000-60000:50000-60000/udp"
    environment:
      - LIVEKIT_EXTERNAL_IP=localhost
      - LIVEKIT_HOST=0.0.0.0
      - LIVEKIT_PORT=7880
    networks:
      - livekit-network
    depends_on:
      - redis
      
  # 2. Redis Database (Mandatory for LiveKit in Production)
  redis:
    image: redis:6-alpine
    container_name: livekit-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - livekit-network
    ports:
      - "6379:6379"

  # 3. Python Deepfake Service
  deepfake-service:
    build:
      context: ../python_deepfake
      dockerfile: Dockerfile
    container_name: deepfake-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - livekit-network

volumes:
  redis_data:

networks:
  livekit-network:
    driver: bridge